######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 28 02:16:42 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
